#!/usr/bin/env python
# pylint: disable=invalid-name
import os
import sys
import uuid
from datetime import datetime, timedelta

from akiri.framework.sqlalchemy import create_engine, get_session
from licensing import License

LICENSE_DAYS = 365

def main():
    if len(sys.argv) != 2:
        script = os.path.basename(sys.argv[0])
        print >> sys.stderr, 'usage: ' + script + ' <name>'
        sys.exit(1)

    data = {'__name__': ''}
    if os.path.exists('application.wsgi'):
        execfile('application.wsgi', data)
    elif os.path.exists('/opt/palette/application.wsgi'):
        execfile('/opt/palette/application.wsgi', data)
    else:
        print >> sys.stderr, "application.wsgi: file not found"
        sys.exit(1)

    create_engine(data['database'], echo=False)

    name = sys.argv[1]

    entry = License.get_by_name(name)
    entry.trial = False
    entry.expiration_time += timedelta(days=LICENSE_DAYS)

    session = get_session()
    session.commit()

if __name__ == '__main__':
    main()
