#!/usr/bin/env python
# pylint: disable=invalid-name
import os
import sys
sys.path.append(os.path.abspath(os.getcwd()))
sys.path.append('/opt/palette')

import sqlalchemy
from akiri.framework.sqlalchemy import Base

# These are need for create_all().
# pylint: disable=unused-import
from billing import Billing
from licensing import License
from support import Support
from stage import Stage
from product import Product
from system import System
from server_info import ServerInfo
# pylint: enable=unused-import

DATABASE='postgresql://palette:palpass@localhost/licensedb'
def main():
    data = {'__name__': ''}
    execfile('application.wsgi', data)
    engine = sqlalchemy.create_engine(DATABASE, echo=False, pool_size=20, max_overflow=50)
    Base.metadata.create_all(engine)
    Stage.populate()
    Product.populate()
    System.populate()
    ServerInfo.populate()

if __name__ == '__main__':
    main()
