#!/usr/bin/env python
# pylint: disable=invalid-name
import sys
sys.path.append('/opt/palette')

import sqlalchemy
from akiri.framework.sqlalchemy import Base

# These are need for create_all().
# pylint: disable=unused-import
from licensing import License
from support import Support
# pylint: enable=unused-import

def main():
    data = {'__name__': ''}
    execfile('application.wsgi', data)
    engine = sqlalchemy.create_engine(data['database'], echo=False)
    Base.metadata.create_all(engine)

if __name__ == '__main__':
    main()
