#!/usr/bin/env python

import sys
import argparse
import boto.iam

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('name')
    parser.add_argument('--region', default='us-east-1')
    args = parser.parse_args()

    iam_name = args.name
    bucket_name = 'production-' + args.name

    iam = boto.iam.connect_to_region('universal')
    if iam is None:
        print >> sys.stderr, 'Invalid region specified for IAM.'
        return 1

    iam.delete_user(iam_name)

    s3 = boto.s3.connect_to_region(args.region)
    if s3 is None:
        print >> sys.stderr, 'Invalid region specified for S3.'
        return 1

    s3.delete_bucket(bucket_name)

    return 0

if __name__ == '__main__':
    sys.exit(main())
