#!/usr/bin/env python
import sys
sys.path.append('/opt/palette')

import logging

from akiri.framework.sqlalchemy import create_engine

from license_manager import LicenseManager

DATABASE = 'postgresql://palette:palpass@localhost/licensedb'

# pylint: disable=invalid-name
database = DATABASE
create_engine(database, echo=False, pool_size=20, max_overflow=30)

# Setup logging
logger = logging.getLogger('licensing')
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.INFO)
formatter = logging.Formatter(\
                    '%(asctime)s - %(name)s - %(levelname)s - %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('--fullname', required=True)
    parser.add_argument('--name', required=True)
    parser.add_argument('--email', required=True)
    args = parser.parse_args()

    parts = args.fullname.split(' ')
    fn = parts[0]
    ln = parts[1]

    data = {'firstname':fn,
            'lastname':ln,
            'email':args.email,
            'name':args.name}

    LicenseManager.new_license(data)
