#!/usr/bin/env python
# pylint: disable=invalid-name
import sys
sys.path.append('/opt/palette')

import os
import uuid
from datetime import datetime, timedelta

from akiri.framework.sqlalchemy import get_session
from licensing import License

TRIAL_DAYS = 14

def main():
    if len(sys.argv) != 2:
        script = os.path.basename(sys.argv[0])
        print >> sys.stderr, 'usage: ' + script + ' <name>'
        sys.exit(1)

    data = {'__name__': ''}
    if os.path.exists('application.wsgi'):
        execfile('application.wsgi', data)
    elif os.path.exists('/opt/palette/application.wsgi'):
        execfile('/opt/palette/application.wsgi', data)
    else:
        print >> sys.stderr, "application.wsgi: file not found"
        sys.exit(1)

    name = sys.argv[1]
    license_key = str(uuid.uuid4()) # V4, entirely random UUID.

    entry = License()
    entry.name = name
    entry.key = license_key
    entry.trial = True
    entry.expiration_time = datetime.utcnow() + timedelta(days=TRIAL_DAYS)

    session = get_session()
    session.add(entry)
    session.commit()

    print 'ID: ' + str(entry.id)
    print 'LICENSE: ' + entry.key


if __name__ == '__main__':
    main()
