#!/usr/bin/env python
# pylint: disable=invalid-name
import sys
sys.path.append('/opt/palette')

import logging
from datetime import datetime

from akiri.framework.sqlalchemy import create_engine

from contact import Email
from product import Product
from ansible_api import AnsibleAPI
from salesforce_api import SalesforceAPI

from trial import generate_license

DATABASE = 'postgresql://palette:palpass@localhost/licensedb'

database = DATABASE
create_engine(database, echo=False, pool_size=20, max_overflow=30)

# Setup logging
logger = logging.getLogger('licensing')
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.INFO)
formatter = logging.Formatter(\
                    '%(asctime)s - %(name)s - %(levelname)s - %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('--fullname',
        help='Set the fullname for the license. Has to be "Firstname Lastname',
        required=True)
    parser.add_argument('--email',
        help='Sets the email address for the license',
        required=True)
    parser.add_argument('--name',
        help='Sets the unique license name', default=None,
        required=False)
    parser.add_argument('--stage',
        help='Sets the stage. If not specified uses STAGE-TRIAL-REQUESTED',
        required=False,
        choices=['STAGE-TRIAL-REQUESTED', 'STAGE-CLOSED-WON'])
    parser.add_argument('--expires',
        help='Sets expiration date. Has to be in the format MM/DD/YY',
        required=False)
    parser.add_argument('--product',
        help='Sets the Product',
        required=False, default=Product.PRO_KEY,
        choices=[Product.PRO_KEY, Product.ENT_KEY])
    parser.add_argument('--send_email',
        help='Send an email to the user. '
             'If not specified no email will be sent',
        required=False, default=False,
        action='store_true')
    parser.add_argument('--slack',
        help='Send the usual Slack messages',
        required=False, default=False,
        action='store_true')
    parser.add_argument('--launch',
        help='Launch an instance. If not specified no instance is launched',
        required=False, default=False,
        action='store_true')
    args = parser.parse_args()

    parts = args.fullname.split(' ')
    fname = parts[0]
    lname = parts[1]
    email = Email(args.email)

    if args.product == 'PALETTE-PRO':
        mailid = 'SENDWITHUS-TRIAL-REQUESTED-PRO-ID'
    else:
        mailid = 'SENDWITHUS-TRIAL-REQUESTED-ENT-ID'

    if args.expires is not None:
        expiration = datetime.strptime(args.expires, '%x')
    else:
        expiration = None # use default

    if args.stage is not None:
        stage = args.stage
    else:
        stage = 'STAGE-TRIAL-REQUESTED'

    # FIXME: create if needed.
    sf = SalesforceAPI.connect()
    contact = SalesforceAPI.get_contact_by_email(sf, email.base)
    if contact is None:
        contact_id = SalesforceAPI.create_contact(sf, fname, lname, email,
                                                  slack=args.slack)
        contact = sf.Contact.get(contact_id)

    product = Product.get_by_key(args.product)

    entry = generate_license(sf, contact, product, name=args.name,
                             stage_key=stage, expiration=expiration,
                             send_email=args.send_email,
                             slack=args.slack)

    if args.product == 'PALETTE-PRO' and args.launch:
        AnsibleAPI.launch_instance(entry, contact,
                                  'PALETTECLOUD-LAUNCH-SUCCESS-ID',
                                  'PALETTECLOUD-LAUNCH-FAIL-ID')

    sys.exit(0)
