#!/usr/bin/env python
# pylint: disable=invalid-name
import os
import sys
sys.path.append(os.path.abspath(os.getcwd()))
sys.path.append('/opt/palette')

import uuid
from datetime import datetime, timedelta

from akiri.framework.sqlalchemy import get_session
from stage import Stage
from licensing import License

TRIAL_DAYS = 14

def main():
    if len(sys.argv) != 2:
        script = os.path.basename(sys.argv[0])
        print >> sys.stderr, 'usage: ' + script + ' <name>'
        sys.exit(1)

    data = {'__name__': ''}
    if os.path.exists('application.wsgi'):
        execfile('application.wsgi', data)
    elif os.path.exists('/opt/palette/application.wsgi'):
        execfile('/opt/palette/application.wsgi', data)
    else:
        print >> sys.stderr, "application.wsgi: file not found"
        sys.exit(1)

    name = sys.argv[1]
    license_key = str(uuid.uuid4()) # V4, entirely random UUID.

    entry = License()
    entry.name = name
    entry.email = name + "@palette-software.com"
    entry.firstname = "Jack"
    entry.lastname = "User"
    entry.key = license_key
    entry.stageid = Stage.get_by_key('STAGE-VERIFIED')
    entry.expiration_time = datetime.utcnow() + timedelta(days=TRIAL_DAYS)

    session = get_session()
    session.add(entry)
    session.commit()

    print 'ID: ' + str(entry.id)
    print 'LICENSE: ' + entry.key


if __name__ == '__main__':
    main()
