#!/usr/bin/env python
# pylint: disable=invalid-name
import sys
sys.path.append('/opt/palette')

import os

from akiri.framework.sqlalchemy import get_session
from licensing import License
from support import Support

LICENSE_DAYS = 365

def main():
    if len(sys.argv) != 3:
        script = os.path.basename(sys.argv[0])
        print >> sys.stderr, 'usage: ' + script + ' <name> <port>'
        sys.exit(1)

    data = {'__name__': ''}
    if os.path.exists('application.wsgi'):
        execfile('application.wsgi', data)
    elif os.path.exists('/opt/palette/application.wsgi'):
        execfile('/opt/palette/application.wsgi', data)
    else:
        print >> sys.stderr, "application.wsgi: file not found"
        sys.exit(1)

    name = sys.argv[1]
    try:
        port = int(sys.argv[2])
    except StandardError:
        print >> sys.stderr, "'port' must be a number."
        sys.exit(1)

    session = get_session()
    entry = Support.get_by_name(name)
    if entry is None:
        license_entry = License.get_by_name(name)
        if license_entry is None:
            print >> sys.stderr, "'" + name + "' not found."
            sys.exit(1)

        entry = Support()
        entry.license_id = license_entry.id
        session.add(entry)

    entry.port = port
    session.commit()

if __name__ == '__main__':
    main()
